"""Score the prepared demo transcript and export timed results for playback."""

import hashlib
import json

import av

from backend.detector import MODEL_PATH, detect
from ml.prepare_data import ROOT


def score_demo(demo: dict) -> dict:
    source = ROOT / "web/public" / demo["audio"].lstrip("/")
    with av.open(str(source)) as audio:
        duration_seconds = audio.duration / av.time_base
    segments = []
    heard = []
    previous_end = 0
    for segment in demo["segments"]:
        if (
            not segment["text"].strip()
            or segment["speaker"] not in {"Caller", "Recipient"}
            or not previous_end <= segment["start_seconds"] < segment["end_seconds"] <= duration_seconds
        ):
            raise ValueError(f"Invalid transcript speaker, text or timing: {demo['id']}")
        previous_end = segment["end_seconds"]
        # Speaker labels are display-only; classify the conversation text as before.
        heard.append(segment["text"])
        segments.append({
            **segment,
            "detection": detect("\n\n".join(heard)).model_dump(),
        })
    if not segments:
        raise ValueError(f"Empty transcript: {demo['id']}")
    return {
        **demo,
        "duration_seconds": duration_seconds,
        "audio_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "segments": segments,
    }


def main() -> None:
    transcript = ROOT / "web/src/demo-transcript.json"
    transcript_hash = hashlib.sha256(transcript.read_bytes()).hexdigest()
    model_hash = hashlib.sha256(MODEL_PATH.read_bytes()).hexdigest()
    demo = {
        **score_demo(json.loads(transcript.read_text())),
        "transcript_sha256": transcript_hash,
        "model_sha256": model_hash,
    }
    (ROOT / "web/src/demo.js").write_text(
        "// Generated by python -m ml.export_demo. Saved results, not live analysis.\n"
        + "export default " + json.dumps(demo, indent=2, ensure_ascii=False) + ";\n"
    )
    print("Exported the demo with saved model results.")


if __name__ == "__main__":
    main()
