"""Save real pipeline output for the static website's prerecorded demo."""

import hashlib
import json
import shutil

from backend.detector import MODEL_PATH, detect
from backend.transcription import transcribe_stream
from ml.prepare_data import ROOT


def main() -> None:
    source = ROOT / "data/audio/possible_scam.m4a"
    segments = []
    heard = []
    for segment in transcribe_stream(source):
        heard.append(segment.text)
        segments.append({
            **segment.model_dump(),
            "detection": detect("\n\n".join(heard)).model_dump(),
        })
    if not segments:
        raise ValueError("Demo recording contains no recognised speech.")
    demo = {
        "audio": "/demo/possible_scam.m4a",
        "description": "Prerecorded demo: saved Whisper transcript and MiniLM scores, no live analysis.",
        "audio_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "model_sha256": hashlib.sha256(MODEL_PATH.read_bytes()).hexdigest(),
        "segments": segments,
    }
    destination = ROOT / "web/public/demo/possible_scam.m4a"
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    (ROOT / "web/src/demo.js").write_text(
        "// Generated by python -m ml.export_demo. Saved results, not live analysis.\n"
        + "export default " + json.dumps(demo, indent=2) + ";\n"
    )
    print(f"Exported {len(segments)} transcript segments with saved model results.")


if __name__ == "__main__":
    main()
