// Generated by python -m ml.export_demo. Saved results, not live analysis.
export default {
  "audio": "/demo/possible_scam.m4a",
  "description": "Prerecorded demo: saved Whisper transcript and MiniLM scores, no live analysis.",
  "audio_sha256": "ee4eb958e7c3f6efcb9cafdb8311eb37ff6e9ade489a781a4dc43dab5392b6ff",
  "model_sha256": "abd240fdd2c522e2bf14fd9717375192762dcd474bb48176b2d7509095f131d8",
  "segments": [
    {
      "text": "Hello, is this Mrs. Imeri? I'm calling from Zurich",
      "start_seconds": 0.0,
      "end_seconds": 3.22,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.0019294132944196463,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "University Hospital.",
      "start_seconds": 3.22,
      "end_seconds": 4.28,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.0018330999882891774,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "Your daughter was involved in a serious car accident.",
      "start_seconds": 4.9,
      "end_seconds": 7.18,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.0017707152292132378,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "I need your help with the assurance.",
      "start_seconds": 7.66,
      "end_seconds": 9.16,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.0017426061676815152,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "Oh my god, is she okay?",
      "start_seconds": 9.92,
      "end_seconds": 11.12,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.001740484032779932,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "She's stable, but we need to process an urgent hospital payment.",
      "start_seconds": 11.76,
      "end_seconds": 14.9,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.7176011800765991,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "Her assurance card was declined.",
      "start_seconds": 15.3,
      "end_seconds": 16.76,
      "speaker": null,
      "detection": {
        "warning": false,
        "score": 0.007306723389774561,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "text": "I need your card number to process the payment.",
      "start_seconds": 17.4,
      "end_seconds": 19.34,
      "speaker": null,
      "detection": {
        "warning": true,
        "score": 0.9983248114585876,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "text": "My card number?",
      "start_seconds": 19.6,
      "end_seconds": 20.46,
      "speaker": null,
      "detection": {
        "warning": true,
        "score": 0.9982954859733582,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "text": "Yes, miss, please hurry up.",
      "start_seconds": 20.8,
      "end_seconds": 22.22,
      "speaker": null,
      "detection": {
        "warning": true,
        "score": 0.9983277916908264,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    }
  ]
};
