// Generated by python -m ml.export_demo. Saved results, not live analysis.
export default {
  "id": "social-security",
  "title": "Social Security impersonation",
  "audio": "/demo/social-security.mp3",
  "source_note": "A scripted demo call: a fake Social Security officer threatens to suspend benefits and asks for a Social Security number.",
  "segments": [
    {
      "speaker": "Recipient",
      "start_seconds": 0.0,
      "end_seconds": 3.56,
      "text": "Hello, this is Mr. Johnson speaking. Who's calling?",
      "detection": {
        "warning": false,
        "score": 0.0018618195317685604,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 4.3,
      "end_seconds": 7.9,
      "text": "My name is Officer Miller, and I'm calling from the Social Security Administration.",
      "detection": {
        "warning": false,
        "score": 0.0018208061810582876,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 8.88,
      "end_seconds": 9.4,
      "text": "Okay.",
      "detection": {
        "warning": false,
        "score": 0.0018015134846791625,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 10.16,
      "end_seconds": 13.86,
      "text": "We've been trying to reach you, sir. There's been a problem with your social security number.",
      "detection": {
        "warning": false,
        "score": 0.0017093258211389184,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 14.48,
      "end_seconds": 15.66,
      "text": "What kind of problem?",
      "detection": {
        "warning": false,
        "score": 0.0016866977093741298,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 16.28,
      "end_seconds": 19.98,
      "text": "It's been compromised and we need to verify some information to secure your account.",
      "detection": {
        "warning": false,
        "score": 0.5918494462966919,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 21.04,
      "end_seconds": 22.74,
      "text": "Compromised? What do you mean?",
      "detection": {
        "warning": false,
        "score": 0.04412739351391792,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 23.56,
      "end_seconds": 26.24,
      "text": "I'm not at liberty to disclose that information over the phone,",
      "detection": {
        "warning": false,
        "score": 0.9210999011993408,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 26.24,
      "end_seconds": 29.12,
      "text": "but I need to confirm your social security number to proceed.",
      "detection": {
        "warning": true,
        "score": 0.9892907738685608,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 29.62,
      "end_seconds": 31.6,
      "text": "This is a matter of utmost importance.",
      "detection": {
        "warning": true,
        "score": 0.9612966179847717,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 32.2,
      "end_seconds": 34.78,
      "text": "If you don't cooperate, your benefits may be suspended.",
      "detection": {
        "warning": true,
        "score": 0.996885359287262,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 35.46,
      "end_seconds": 37.62,
      "text": "Please state your social security number to proceed.",
      "detection": {
        "warning": true,
        "score": 0.9973258972167969,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 38.36,
      "end_seconds": 40.1,
      "text": "Okay, let me get my card.",
      "detection": {
        "warning": true,
        "score": 0.99809330701828,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 40.7,
      "end_seconds": 41.08,
      "text": "Sure.",
      "detection": {
        "warning": true,
        "score": 0.9980567097663879,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 41.72,
      "end_seconds": 48.84,
      "text": "Okay, my number is 8293-4838.",
      "detection": {
        "warning": true,
        "score": 0.9980213642120361,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    }
  ],
  "duration_seconds": 49.240813,
  "audio_sha256": "068386dc611feecf8e0ad65251607db0b1c846f510086d2c8d2e27e404af4ea4",
  "transcript_sha256": "34e23113a64d85e4c1fa51cb5c5f01f5c52aaa1b64728ccdf551c707a6e1ec74",
  "model_sha256": "abd240fdd2c522e2bf14fd9717375192762dcd474bb48176b2d7509095f131d8"
};
