// Generated by python -m ml.export_demo. Saved results, not live analysis.
export default {
  "id": "westpac",
  "title": "Westpac · Card details",
  "audio": "/demo/westpac-card.wav",
  "source_title": "Westpac NZ: Scammer in action",
  "source_url": "https://www.westpac.co.nz/about-us/media/westpac-releases-recording-of-scammer-in-action/",
  "source_start_seconds": 135.1,
  "source_end_seconds": 161.0,
  "source_note": "A real customer call published by a Westpac Bank. A fake bank employee asks for credit card digits.",
  "segments": [
    {
      "speaker": "Recipient",
      "start_seconds": 0.195,
      "end_seconds": 2.145,
      "text": "Digit after eight? What does that mean?",
      "detection": {
        "warning": false,
        "score": 0.007583041675388813,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 2.735,
      "end_seconds": 7.505,
      "text": "Yeah, so on the credit card there that you can see beginning five, four, three, six, seven, eight.",
      "detection": {
        "warning": false,
        "score": 0.0061571309342980385,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 7.575,
      "end_seconds": 8.3,
      "text": "Yeah, yeah.",
      "detection": {
        "warning": false,
        "score": 0.007201252970844507,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 8.3,
      "end_seconds": 10.825,
      "text": "We need to confirm the digits after eight for cancellation.",
      "detection": {
        "warning": false,
        "score": 0.8700177073478699,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": ""
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 11.525,
      "end_seconds": 15.545,
      "text": "After that you'll be receiving a text message from us, and then that will be cancelled.",
      "detection": {
        "warning": true,
        "score": 0.9974746108055115,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Recipient",
      "start_seconds": 16.365,
      "end_seconds": 20.385,
      "text": "You can't just do it straight away? Do I need to respond to the text?",
      "detection": {
        "warning": true,
        "score": 0.9969956874847412,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    },
    {
      "speaker": "Caller",
      "start_seconds": 21.125,
      "end_seconds": 25.745,
      "text": "Yep, so we'll send you the text message after we've cancelled the card for you, what we're doing now for you.",
      "detection": {
        "warning": true,
        "score": 0.9976143836975098,
        "threshold": 0.9500000000000001,
        "signals": [],
        "reason": "Possible scam: this conversation resembles scam requests in the training examples. Pause and verify the caller independently."
      }
    }
  ],
  "duration_seconds": 25.9,
  "audio_sha256": "38e0322a1d86e782f8721e1b79057a3de1fead05e432d0fb9147dbe3998fbd2f",
  "transcript_sha256": "f03f1d5df5437b3b17e76ee6cf277d137becc9ae9b5143477879aa28235caac1",
  "model_sha256": "abd240fdd2c522e2bf14fd9717375192762dcd474bb48176b2d7509095f131d8"
};
